require("dotenv").config();
const express=require("express"),cors=require("cors"),Database=require("better-sqlite3"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),path=require("path"),fs=require("fs");
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"CHANGE_ME";
app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
fs.mkdirSync(path.join(__dirname,"data"),{recursive:true});
const db=new Database(path.join(__dirname,"data","qta.db"));db.pragma("journal_mode = WAL");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,role TEXT,username TEXT UNIQUE,password_hash TEXT,mobile TEXT,email TEXT,age INTEGER,hospital_name TEXT,hospital_id TEXT,unique_id TEXT UNIQUE,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cases(id INTEGER PRIMARY KEY,patient_user_id INTEGER,patient_name TEXT,age INTEGER,problem TEXT,location_status TEXT,hospital_id TEXT,status TEXT DEFAULT 'registered',risk_level TEXT,news_score INTEGER,rr REAL,spo2 REAL,sbp REAL,heart_rate REAL,consciousness TEXT,temperature REAL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY,patient_user_id INTEGER,hospital_id TEXT,message TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY,hospital_id TEXT UNIQUE,low_max INTEGER DEFAULT 4,medium_max INTEGER DEFAULT 6,medium_review_minutes INTEGER DEFAULT 30,updated_by INTEGER,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const hid=x=>String(x||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,4);
function uid(role,h=""){let s=role==="patient"?"":hid(h),n=10-s.length,x;do{x="";while(x.length<n)x+=Math.floor(Math.random()*10);x+=s}while(db.prepare("SELECT 1 FROM users WHERE unique_id=?").get(x));return x}
function auth(req,res,next){let t=(req.headers.authorization||"").replace("Bearer ","");if(!t)return res.status(401).json({error:"Please log in"});try{req.user=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({error:"Invalid session"})}}
const only=(...r)=>(req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({error:"Access denied"});
function settings(h){let s=db.prepare("SELECT * FROM settings WHERE hospital_id=?").get(h);if(!s){db.prepare("INSERT OR IGNORE INTO settings(hospital_id) VALUES(?)").run(h);s=db.prepare("SELECT * FROM settings WHERE hospital_id=?").get(h)}return s}
const rr=x=>x<=8?3:x<=11?1:x<=20?0:x<=24?2:3,sp=x=>x<=91?3:x<=93?2:x<=95?1:0,bp=x=>x<=90?3:x<=100?2:x<=110?1:x<=219?0:3,hr=x=>x<=40?3:x<=50?1:x<=90?0:x<=110?1:x<=130?2:3,tp=x=>x<=35?3:x<=36?1:x<=38?0:x<=39?1:2,co=x=>String(x).toLowerCase()==="alert"?0:3;
function triage(v,h){let score=rr(+v.rr)+sp(+v.spo2)+bp(+v.sbp)+hr(+v.heart_rate)+tp(+v.temperature)+co(v.consciousness),s=settings(h);return{score,risk:score<=s.low_max?"LOW":score<=s.medium_max?"MEDIUM":"HIGH"}}

app.post("/api/auth/register",(req,res)=>{let {role,username,password,mobile,email,age,hospital_name,hospital_id}=req.body;if(!["patient","nurse","doctor"].includes(role)||!username||!password||!mobile)return res.status(400).json({error:"Complete required fields"});if(role==="patient"&&!age)return res.status(400).json({error:"Age required"});if(role!=="patient"&&(!hospital_name||!hospital_id))return res.status(400).json({error:"Hospital details required"});try{let u=uid(role,hospital_id),info=db.prepare("INSERT INTO users(role,username,password_hash,mobile,email,age,hospital_name,hospital_id,unique_id) VALUES(?,?,?,?,?,?,?,?,?)").run(role,username,bcrypt.hashSync(password,10),mobile,email||null,age||null,hospital_name||null,hid(hospital_id)||null,u),user={id:info.lastInsertRowid,role,username,unique_id:u,hospital_id:hid(hospital_id)||null};res.json({user,token:jwt.sign(user,SECRET,{expiresIn:"12h"})})}catch(e){res.status(400).json({error:"Username already exists"})}});
app.post("/api/auth/login",(req,res)=>{let u=db.prepare("SELECT * FROM users WHERE username=?").get(req.body.username);if(!u||u.role!==req.body.role||!bcrypt.compareSync(req.body.password||"",u.password_hash))return res.status(401).json({error:"Invalid login"});let user={id:u.id,role:u.role,username:u.username,unique_id:u.unique_id,hospital_id:u.hospital_id};res.json({user,token:jwt.sign(user,SECRET,{expiresIn:"12h"})})});
app.post("/api/cases",auth,only("patient"),(req,res)=>{let v=req.body;if(!v.patient_name||!v.age||!v.problem||!v.location_status)return res.status(400).json({error:"Complete the form"});let r=db.prepare("INSERT INTO cases(patient_user_id,patient_name,age,problem,location_status,hospital_id) VALUES(?,?,?,?,?,?)").run(req.user.id,v.patient_name,v.age,v.problem,v.location_status,hid(v.hospital_id)||null);res.json({id:r.lastInsertRowid})});
app.get("/api/cases/my",auth,only("patient"),(req,res)=>res.json(db.prepare("SELECT * FROM cases WHERE patient_user_id=? ORDER BY datetime(updated_at) DESC").all(req.user.id)));
app.get("/api/cases",auth,only("nurse","doctor"),(req,res)=>res.json(db.prepare("SELECT c.*,u.unique_id patient_id FROM cases c JOIN users u ON u.id=c.patient_user_id WHERE c.hospital_id=? OR c.hospital_id IS NULL ORDER BY CASE c.risk_level WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 WHEN 'LOW' THEN 3 ELSE 4 END,datetime(c.updated_at) DESC").all(req.user.hospital_id)));
app.post("/api/cases/:id/triage",auth,only("nurse"),(req,res)=>{let c=db.prepare("SELECT * FROM cases WHERE id=?").get(req.params.id),v=req.body;if(!c)return res.status(404).json({error:"Case not found"});for(let k of ["rr","spo2","sbp","heart_rate","consciousness","temperature"])if(v[k]===undefined||v[k]==="")return res.status(400).json({error:"All six measurements are required"});let z=triage(v,c.hospital_id||req.user.hospital_id),status=z.risk==="HIGH"?"doctor_queue":"triaged";db.prepare("UPDATE cases SET rr=?,spo2=?,sbp=?,heart_rate=?,consciousness=?,temperature=?,news_score=?,risk_level=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(v.rr,v.spo2,v.sbp,v.heart_rate,v.consciousness,v.temperature,z.score,z.risk,status,c.id);res.json({...z,status})});
app.post("/api/cases/:id/transfer",auth,only("nurse"),(req,res)=>{db.prepare("UPDATE cases SET status='doctor_queue',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.params.id);res.json({message:"Transferred"})});
app.get("/api/doctor/queue",auth,only("doctor"),(req,res)=>res.json(db.prepare("SELECT c.*,u.unique_id patient_id FROM cases c JOIN users u ON u.id=c.patient_user_id WHERE c.hospital_id=? AND c.status='doctor_queue' ORDER BY CASE c.risk_level WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END,datetime(c.updated_at)").all(req.user.hospital_id)));
app.post("/api/cases/:id/status",auth,only("doctor"),(req,res)=>{let a=["under_review","completed","admitted","follow_up"];if(!a.includes(req.body.status))return res.status(400).json({error:"Invalid status"});db.prepare("UPDATE cases SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.body.status,req.params.id);res.json({message:"Updated"})});
app.get("/api/settings",auth,only("doctor"),(req,res)=>res.json(settings(req.user.hospital_id)));
app.put("/api/settings",auth,only("doctor"),(req,res)=>{let v=req.body;if(+v.low_max<0||+v.medium_max<+v.low_max)return res.status(400).json({error:"Invalid settings"});db.prepare("INSERT INTO settings(hospital_id,low_max,medium_max,medium_review_minutes,updated_by,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(hospital_id) DO UPDATE SET low_max=excluded.low_max,medium_max=excluded.medium_max,medium_review_minutes=excluded.medium_review_minutes,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP").run(req.user.hospital_id,v.low_max,v.medium_max,v.medium_review_minutes,req.user.id);res.json(settings(req.user.hospital_id))});
app.post("/api/messages",auth,only("patient"),(req,res)=>{if(!req.body.message?.trim())return res.status(400).json({error:"Message required"});db.prepare("INSERT INTO messages(patient_user_id,hospital_id,message) VALUES(?,?,?)").run(req.user.id,hid(req.body.hospital_id)||null,req.body.message.trim());res.json({message:"Sent"})});
app.get("/api/messages",auth,only("nurse"),(req,res)=>res.json(db.prepare("SELECT m.*,u.username,u.unique_id FROM messages m JOIN users u ON u.id=m.patient_user_id WHERE m.hospital_id=? OR m.hospital_id IS NULL ORDER BY datetime(m.created_at) DESC").all(req.user.hospital_id)));
app.get("/api/history",auth,(req,res)=>{if(req.user.role==="patient")return res.json(db.prepare("SELECT * FROM cases WHERE patient_user_id=? ORDER BY datetime(updated_at) DESC").all(req.user.id));res.json(db.prepare("SELECT * FROM cases WHERE hospital_id=? ORDER BY date(updated_at) DESC,datetime(updated_at) DESC").all(req.user.hospital_id))});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("QTA running on "+PORT));